### ISSUE TITLE
Doubling of equations in athena PDF output

### ISSUE THREAD

**Issue by berceanu** [manubot/rootstock#252] opened 2019-07-10 11:30 UTC
When comparing the [HTML output](https://berceanu.github.io/lwfa_scaling/) with the [PDF output](https://berceanu.github.io/lwfa_scaling/manuscript.pdf) of my manuscript, I noticed all the (non-inline) formulas appear twice in the `.pdf`. Here is the original [repo](https://github.com/berceanu/lwfa_scaling).

**Comment by agitter** [comment] 2019-07-10 13:58
This could possibly be related to using Athena to build the PDF.  When I locally built this manuscript during the BOM testing I used weasyprint.  The equations weren't duplicated:
[manuscript.pdf](https://github.com/manubot/rootstock/files/3377827/manuscript.pdf)

It may also be relevant that the two copies of the equations use different fonts.

**Comment by dhimmel** [comment] 2019-07-10 15:09
[Here's a permalink](https://berceanu.github.io/lwfa_scaling/v/6cbf02dc6d1c6cbba15b49d6b418823357fd9c34/manuscript.pdf) to the PDF with the duplicated equations. One interesting thing is that the duplications are not present on the final few pages.

Here is our current athenapdf command:

https://github.com/manubot/rootstock/blob/2a5e425650947020d2d4b49447e3f3d9718dee40/build/build.sh#L90-L98

I wonder if increasing the delay from 2 seconds would help? Perhaps the page is still rendering. When I [print the HTML to PDF](https://berceanu.github.io/lwfa_scaling/v/6cbf02dc6d1c6cbba15b49d6b418823357fd9c34/) in Chrome, I don't get duplications. This should be a similar process as what Athena is doing (albeit with different versions of dependencies). @berceanu has this happened multiple times? If you rerun CI will that fix it? In other words, is this an intermittent error.

@vincerubinetti any ideas?

> When I locally built this manuscript during the BOM testing I used weasyprint. The equations weren't duplicated

@agitter I thought that equations didn't render with WeasyPrint because they require javascript. That is bizarre

**Comment by berceanu** [comment] 2019-07-10 16:37
Might also be solved if https://github.com/manubot/rootstock/issues/249 is addressed.

**Comment by vincerubinetti** [comment] 2019-07-10 17:10
I think I have a good idea of what is causing this. These equations are being rendered with MathJax right?

MathJax has two methods of displaying equations (that I know of): 1) with unicode and regular text characters attempting to convey the same symbols, using approximations where necessary and 2) with svg symbols that can get you exactly what you need. If you look in the output html of an equation, I think you'll see a `<div>` called something like `mathjax-preview`, which is method 1). I believe that is what loads first on the html, with 2) replacing it when it's ready. And I suppose 1) is also there as a fallback for browsers that don't support svg.

There's probably some issue with 1) being removed when being rendered with athena. I'll look into it.

If possible, I'd like to remove that whole "preview" 1) method completely, as every browser now supports svg, and it doesn't seem to take that long to render the symbols.

**Comment by slochower** [comment] 2019-07-10 17:12
@vincerubinetti also check `    --delay=2000 ` in the build script. I hypothesize increasing this might leave enough time for all equations to be replaced with SVG icons.

**Comment by vincerubinetti** [comment] 2019-07-10 19:45
@slochower Maybe. It does look like a couple of the equations near the end of the paper never got converted from text to svg. But I would think that they'd replace each equation after it's done, not wait to replace them all until they're all done.

Also, it looks like the inline equations haven't been converted from text to svg at all. Maybe the inline equations are done after all the out-of-line equations are finished?

Either way, should increase the delay and also get rid of the text preview. It looks ugly and should never be there. All the browsers and printing devices we support in general also support SVG.

**Comment by vincerubinetti** [comment] 2019-07-10 19:57
Related:
https://github.com/mathjax/MathJax/issues/1730

My guess as to the order that MathJax processes things in:

The HTML has some raw Latex syntax in it. MJ scans for that text and uses a (quick?) method ("fast preview") to convert the latex into raw text/unicode symbols. Then, MJ goes through those same elements all over again, adding svg versions of the equations one by one. When they're all done, then it removes the fast preview text and leaves only the svgs.

Does that sound right?

In such a case, I guess maybe it wouldn't be a good idea to remove "fast preview" because then it would (presumably) leave the original latex input as raw text until the svgs were finished rendering.

Ideally, I'd just like remove all the equation text and show nothing until the svgs are finished. Maybe I can just target the latex and mathjax fast preview classes in CSS and make them invisible that way. That way, if you ever see an equation missing, you know exactly what the problem is: you just have to increase the time allowed for the javascript to run when printing.

This is all assuming that this preview thing is the issue to begin with, of course.

**Comment by dhimmel** [comment] 2019-07-11 19:11
@vincerubinetti seems like you've got some ideas on how to improve the MathJax integration. I forgot, are we controlling the version of MathJax that is used? If so, we should probably update that as well.

Also let's make sure that whatever solution doesn't worsen the current experience for users with javascript enabled. However, I agree that it's safe to assume any user with JS (or without JS) can load SVGs.

I also wonder if we should increase the default `--delay` for Athena. 2 seconds does seem like a lot... would 3 change things that much?

**Comment by berceanu** [comment] 2019-07-15 10:24
Found a nice markdown-to-latex template for inspiration: https://github.com/Wandmalfarbe/pandoc-latex-template

**Comment by agitter** [comment] 2019-07-16 15:45
@berceanu did you find a way to resolve the double equation issue?  The latest manuscript no longer has them: [permalink](https://berceanu.github.io/lwfa_scaling/v/4daaeed7ea7d2ca3476ce9fb0411b07d8c0961b5/manuscript.pdf)

**Comment by berceanu** [comment] 2019-07-16 15:56
No, I didn't change anything. I just merged the upstream changes, did you guys change something?

**Comment by agitter** [comment] 2019-07-16 16:06
The upstream changes you merged in https://github.com/berceanu/lwfa_scaling/pull/4/files were related to the deploy process in Travis CI, the documentation, and the setup process.  Nothing that should have affected manuscript content.  Maybe it was an intermittent problem?

**Comment by berceanu** [comment] 2019-07-16 16:08
Could be. Feel free to close this, I'll append to it if the problem reappears. Either way, the PDF looks *much* nicer when exported via LaTeX, imho.

**Comment by dhimmel** [comment] 2019-07-30 14:41
> the PDF looks much nicer when exported via LaTeX, imho

Noting https://github.com/manubot/rootstock/issues/249 to track our progress with LaTeX output.

We will close this issue with https://github.com/manubot/rootstock/pull/255.

**Closed** 2019-08-04 19:26 UTC
