### ISSUE TITLE
First section not separated from abstract

### ISSUE THREAD

**Issue by berceanu** [manubot/rootstock#247] opened 2019-07-05 16:25 UTC
If you look at the rendered html of [my repo](https://github.com/berceanu/lwfa_scaling), the first section is merged together with the abstract, and I can't figure out why, the markdown sources look fine.

**Comment by slochower** [comment] 2019-07-05 16:28
I'm not sure what's happening, at the moment.

I can confirm that the compiled [Markdown](https://github.com/berceanu/lwfa_scaling/blob/output/manuscript.md) looks fine and I can see that the [HTML](https://github.com/berceanu/lwfa_scaling/blob/output/manuscript.html) renders section 1 as `<p>﻿## 1. CPLS parameters</p>`.

**Comment by slochower** [comment] 2019-07-05 16:39
There is a [byte order mark](https://en.wikipedia.org/wiki/Byte_order_mark) embedded in `manuscript.md` before your first section. I'm not sure where this originated. I'm also not sure how to reveal this using `cat` or `head`, but if you open `02.body.md` in `vim`, everything is fine. However, if I open `manuscript.md` in `vim`, then I see this:

![image](https://user-images.githubusercontent.com/5393995/60735505-7f8ccf00-9f08-11e9-9d5e-8ddb84981b9b.png)

`<feff>` is the byte order mark. [Either one of our scripts or your editor put that there erroneously.](https://stackoverflow.com/questions/1972362/why-is-my-bash-script-adding-feff-to-the-beginning-of-files) Because `02.body.md` looks fine and `manuscript.md` does not, I'm incline to believe one of our scripts is doing this (cc @dhimmel).

**Comment by slochower** [comment] 2019-07-05 16:41
One other thing, on reflection, I noticed:

```
$ file 02.body.md
02.body.md: UTF-8 Unicode (with BOM) text, with very long lines
```

I'm not using to seeing the `(with BOM)`. I think it's possible there might be an editor setting to chance the encoding of your file.

**Comment by agitter** [comment] 2019-07-05 17:47
@slochower I see that as well.  On my machine, the byte order mark was visible with `head` but not in `vim`.

I attempted to remove it in https://github.com/berceanu/lwfa_scaling/pull/1 as a test.  If that works, we may want to learn how to avoid this more generally.  Maybe Manubot could remove this character automatically?

**Comment by slochower** [comment] 2019-07-05 17:49
> @slochower I see that as well. On my machine, the byte order mark was visible with head but not in vim.

Interesting. Opposite here. 

> I attempted to remove it in berceanu/lwfa_scaling#1 as a test. If that works, we may want to learn how to avoid this more generally. Maybe Manubot could remove this character automatically?

Your PR looks good to me, @agitter . Also a good thought to consider automatically stripping the BOM and perhaps other encoding errors.

**Comment by berceanu** [comment] 2019-07-05 18:02
Looked at HTML output, the PR fixed the issue. Thanks a lot!
I do wonder if that byte order mark appered there when I exported from [stackedit(https://stackedit.io)/GDrive.

**Comment by agitter** [comment] 2019-07-05 18:36
I'm glad it worked.  I'll close this issue and open a new one for our Manubot Python package to look into stripping the byte order mark.

We'd also love to add your new manuscript to the catalog at https://manubot.org/catalog/ when you're ready.  You can open at issue or make a pull request at https://github.com/manubot/catalog to add it.

**Closed by agitter** 2019-07-05 18:36 UTC
