### ISSUE TITLE
Giant orcid logos in docx output

### ISSUE THREAD

**Issue by ch728** [manubot/rootstock#437] opened 2021-09-02 21:18 UTC
My docx output has giant  orcid logos in  it.  I do not have this problem in the html or pdf output.
![Screenshot from 2021-09-02 16-47-01](https://user-images.githubusercontent.com/36375878/131917468-56ac24cc-b07a-4e0d-b776-38e09d8b97ae.png)

**Comment by agitter** [comment] 2021-09-03 19:03
The issue is that these are svg images and docx readers (especially older versions of Word) do not have great svg support.  There is some historical discussion of that in https://github.com/manubot/rootstock/pull/40.  This is a general pandoc issue, and there was an update within the past week to improve svg docx support https://github.com/jgm/pandoc/issues/4058.

I tested your manuscript.  Word 2016 on Windows doesn't render the svg images at all:
![image](https://user-images.githubusercontent.com/3532898/132054286-0925a341-f518-4e26-9691-f8fd1ed34c15.png)

Some users have modified `content/00.front-matter.md` to remove these images or customize the build script to exclude the images when converting to docx.  Others manually delete them from the docx.  We don't have a good general solution yet.  The next step may be to test the next pandoc release to explore its updated support.

**Comment by twrightsman** [comment] 2021-09-29 15:18
This can be fixed on the rootstock side by manually defining the size of the SVG images in `content/00.front-matter.md`. I used 16px because that's the size defined in the SVG files.

```
diff --git a/content/00.front-matter.md b/content/00.front-matter.md
index 2f01ad2..a9c1b5c 100644
--- a/content/00.front-matter.md
+++ b/content/00.front-matter.md
@@ -25,15 +25,15 @@ on {{manubot.date}}.
 {% for author in manubot.authors %}
 + **{{author.name}}**<br>
   {%- if author.orcid is defined and author.orcid is not none %}
-    ![ORCID icon](images/orcid.svg){.inline_icon}
+    ![ORCID icon](images/orcid.svg){.inline_icon width=16 height=16}
     [{{author.orcid}}](https://orcid.org/{{author.orcid}})
   {%- endif %}
   {%- if author.github is defined and author.github is not none %}
-    · ![GitHub icon](images/github.svg){.inline_icon}
+    · ![GitHub icon](images/github.svg){.inline_icon width=16 height=16}
     [{{author.github}}](https://github.com/{{author.github}})
   {%- endif %}
   {%- if author.twitter is defined and author.twitter is not none %}
-    · ![Twitter icon](images/twitter.svg){.inline_icon}
+    · ![Twitter icon](images/twitter.svg){.inline_icon width=16 height=16}
     [{{author.twitter}}](https://twitter.com/{{author.twitter}})
   {%- endif %}<br>
   <small>
```

@agitter Do you think the workaround is benign enough to merge in to rootstock?

**Comment by dhimmel** [comment] 2021-09-29 17:43
We used to include `height="13px" width="13px"` but that was changed in 658bcd763deae50732867a471d38760a90b13641. Seems like we might want to add them back.

@vincerubinetti did you want to weight in? Do you know whether these logos should be `13px` or `16px`?

**Comment by vincerubinetti** [comment] 2021-09-29 17:45
Either is fine.

**Comment by dhimmel** [comment] 2021-09-29 18:58
@twrightsman do you want to make a PR to rootstock with this change?

**Closed** 2021-09-30 01:04 UTC
